// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: snapshot.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnapShot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceName    string                 `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	Timestamp      int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	GoroutineDump  []byte                 `protobuf:"bytes,3,opt,name=GoroutineDump,proto3" json:"GoroutineDump,omitempty"`
	BlockProfile   []byte                 `protobuf:"bytes,4,opt,name=BlockProfile,proto3" json:"BlockProfile,omitempty"`
	MutexProfile   []byte                 `protobuf:"bytes,5,opt,name=MutexProfile,proto3" json:"MutexProfile,omitempty"`
	RuntimeMetrics map[string]float64     `protobuf:"bytes,6,rep,name=runtime_metrics,json=runtimeMetrics,proto3" json:"runtime_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Version        string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SnapShot) Reset() {
	*x = SnapShot{}
	mi := &file_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapShot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapShot) ProtoMessage() {}

func (x *SnapShot) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapShot.ProtoReflect.Descriptor instead.
func (*SnapShot) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *SnapShot) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SnapShot) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SnapShot) GetGoroutineDump() []byte {
	if x != nil {
		return x.GoroutineDump
	}
	return nil
}

func (x *SnapShot) GetBlockProfile() []byte {
	if x != nil {
		return x.BlockProfile
	}
	return nil
}

func (x *SnapShot) GetMutexProfile() []byte {
	if x != nil {
		return x.MutexProfile
	}
	return nil
}

func (x *SnapShot) GetRuntimeMetrics() map[string]float64 {
	if x != nil {
		return x.RuntimeMetrics
	}
	return nil
}

func (x *SnapShot) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_snapshot_proto protoreflect.FileDescriptor

const file_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x0esnapshot.proto\x12\afetcher\"\xe5\x02\n" +
	"\bSnapShot\x12 \n" +
	"\vServiceName\x18\x01 \x01(\tR\vServiceName\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12$\n" +
	"\rGoroutineDump\x18\x03 \x01(\fR\rGoroutineDump\x12\"\n" +
	"\fBlockProfile\x18\x04 \x01(\fR\fBlockProfile\x12\"\n" +
	"\fMutexProfile\x18\x05 \x01(\fR\fMutexProfile\x12N\n" +
	"\x0fruntime_metrics\x18\x06 \x03(\v2%.fetcher.SnapShot.RuntimeMetricsEntryR\x0eruntimeMetrics\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\x1aA\n" +
	"\x13RuntimeMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01B5Z3github.com/2n1k1ch2/gold/cmd/Agent/fetcher;snapshotb\x06proto3"

var (
	file_snapshot_proto_rawDescOnce sync.Once
	file_snapshot_proto_rawDescData []byte
)

func file_snapshot_proto_rawDescGZIP() []byte {
	file_snapshot_proto_rawDescOnce.Do(func() {
		file_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snapshot_proto_rawDesc), len(file_snapshot_proto_rawDesc)))
	})
	return file_snapshot_proto_rawDescData
}

var file_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_snapshot_proto_goTypes = []any{
	(*SnapShot)(nil), // 0: fetcher.SnapShot
	nil,              // 1: fetcher.SnapShot.RuntimeMetricsEntry
}
var file_snapshot_proto_depIdxs = []int32{
	1, // 0: fetcher.SnapShot.runtime_metrics:type_name -> fetcher.SnapShot.RuntimeMetricsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_snapshot_proto_init() }
func file_snapshot_proto_init() {
	if File_snapshot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snapshot_proto_rawDesc), len(file_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_snapshot_proto_goTypes,
		DependencyIndexes: file_snapshot_proto_depIdxs,
		MessageInfos:      file_snapshot_proto_msgTypes,
	}.Build()
	File_snapshot_proto = out.File
	file_snapshot_proto_goTypes = nil
	file_snapshot_proto_depIdxs = nil
}
